from setuptools import setup

setup(name='pynggdpp',
      version='0.0.1',
      description='Bare bones version of pynggdpp',
      url='http://github.com/nggdpp/pynggdpp',
      author='R. Sky Bristol',
      author_email='sbristol@usgs.gov',
      license='unlicense',
      packages=['pynggdpp'],
      install_requires=[
            'beautifulsoup4',
            'boto3',
            'bs4',
            'certifi',
            'chardet',
            'decorator',
            'defusedxml',
            'elasticsearch',
            'geojson',
            'gis-metadata-parser',
            'idna',
            'numpy',
            'owslib',
            'pandas',
            'parserutils',
            'pymongo',
            'python-dateutil',
            'pytz',
            'requests',
            'six',
            'soupsieve',
            'urllib3',
            'validators',
            'xmltodict'
      ],
      zip_safe=False)
